# Generated by Django 5.1.2 on 2024-10-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_alter_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='reservation_id',
            field=models.CharField(default='<reservation-in-progress>', max_length=100),
        ),
    ]
